"""initial schema

Revision ID: 1dc7b10f88a9
Revises:
Create Date: 2026-02-21 14:54:54.104637

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1dc7b10f88a9"
down_revision: str | list[str] | None = None
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detector",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "metadata",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "posix_group",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pi",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_posix_group",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "posix_group_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["posix_group_name"],
            ["posix_group.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "posix_group_name"),
    )
    op.create_table(
        "experiment",
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pi_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("leader_account", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("posix_group", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pi_id"],
            ["pi.id"],
        ),
        sa.ForeignKeyConstraint(
            ["posix_group"],
            ["posix_group.name"],
        ),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_table(
        "experiment_analysis_queue",
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("queue", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("experiment_id", "queue"),
    )
    op.create_table(
        "experiment_slack_channel",
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_table(
        "questionnaire",
        sa.Column(
            "questionnaire_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("proposal", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("field_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("field_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("field_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("modified_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_uid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("questionnaire_id"),
        sa.UniqueConstraint(
            "experiment_id", "field_id", name="uq_questionnaire_exp_field"
        ),
    )
    op.create_index(
        op.f("ix_questionnaire_experiment_id"),
        "questionnaire",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "run",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_number", "experiment_id", name="uq_run_number_exp"),
    )
    op.create_index(
        op.f("ix_run_experiment_id"), "run", ["experiment_id"], unique=False
    )
    op.create_table(
        "workflowdefinition",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("executable", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "MANUAL",
                "START_OF_RUN",
                "END_OF_RUN",
                "FIRST_FILE_TRANSFERRED",
                "ALL_FILES_TRANSFERRED",
                "ALL_NONREC_FILES_TRANSFERRED",
                "RUN_PARAM_IS_VALUE",
                name="workflow_trigger_type",
            ),
            nullable=False,
        ),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("run_param_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("run_param_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("run_as_user", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflowdefinition_experiment_id"),
        "workflowdefinition",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "logbook",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum("TEXT", "HTML", "MARKDOWN", name="elog_content_type"),
            nullable=False,
        ),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_logbook_experiment_id"), "logbook", ["experiment_id"], unique=False
    )
    op.create_index(op.f("ix_logbook_run_id"), "logbook", ["run_id"], unique=False)
    op.create_table(
        "run_detector",
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detector_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["detector_id"],
            ["detector.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "detector_id"),
    )
    op.create_index(
        op.f("ix_run_detector_experiment_id"),
        "run_detector",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "run_production_data",
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("n_events", sa.BigInteger(), nullable=True),
        sa.Column("n_damaged", sa.BigInteger(), nullable=True),
        sa.Column("n_dropped", sa.BigInteger(), nullable=True),
        sa.Column("start_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_count", sa.BigInteger(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_run_production_data_experiment_id"),
        "run_production_data",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "workflow",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("experiment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("def_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("submit_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tool_id", sa.BigInteger(), nullable=True),
        sa.Column("log_file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["def_id"],
            ["workflowdefinition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflow_def_id"), "workflow", ["def_id"], unique=False)
    op.create_index(
        op.f("ix_workflow_experiment_id"), "workflow", ["experiment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_experiment_id"), table_name="workflow")
    op.drop_index(op.f("ix_workflow_def_id"), table_name="workflow")
    op.drop_table("workflow")
    op.drop_index(
        op.f("ix_run_production_data_experiment_id"), table_name="run_production_data"
    )
    op.drop_table("run_production_data")
    op.drop_index(op.f("ix_run_detector_experiment_id"), table_name="run_detector")
    op.drop_table("run_detector")
    op.drop_index(op.f("ix_logbook_run_id"), table_name="logbook")
    op.drop_index(op.f("ix_logbook_experiment_id"), table_name="logbook")
    op.drop_table("logbook")
    op.drop_index(
        op.f("ix_workflowdefinition_experiment_id"), table_name="workflowdefinition"
    )
    op.drop_table("workflowdefinition")
    op.drop_index(op.f("ix_run_experiment_id"), table_name="run")
    op.drop_table("run")
    op.drop_index(op.f("ix_questionnaire_experiment_id"), table_name="questionnaire")
    op.drop_table("questionnaire")
    op.drop_table("experiment_slack_channel")
    op.drop_table("experiment_analysis_queue")
    op.drop_table("experiment")
    op.drop_table("user_posix_group")
    op.drop_table("pi")
    op.drop_table("user")
    op.drop_table("posix_group")
    op.drop_table("metadata")
    op.drop_table("detector")
    sa.Enum(name="workflow_trigger_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="elog_content_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
