
Enum "workflow_trigger_type" {
  "MANUAL"
  "START_OF_RUN"
  "END_OF_RUN"
  "FIRST_FILE_TRANSFERRED"
  "ALL_FILES_TRANSFERRED"
  "ALL_NONREC_FILES_TRANSFERRED"
  "RUN_PARAM_IS_VALUE"
}

Enum "elog_content_type" {
  "TEXT"
  "HTML"
  "MARKDOWN"
}

Table "detector" {
  "id" TEXT [not null]
  "name" TEXT [unique, not null]
  "description" TEXT

  Indexes {
    id [pk]
  }
}

Table "posix_group" {
  "name" TEXT [not null]

  Indexes {
    name [pk]
  }
}

Table "user" {
  "id" TEXT [not null]

  Indexes {
    id [pk]
  }
}

Table "workflowdefinition" {
  "id" TEXT [not null]
  "name" TEXT [not null]
  "executable" TEXT [not null]
  "trigger" workflow_trigger_type [not null]
  "location" TEXT [not null]
  "parameters" TEXT
  "run_param_name" TEXT
  "run_param_value" TEXT
  "run_as_user" TEXT

  Indexes {
    id [pk]
  }
}

Table "pi" {
  "id" TEXT [not null]
  "name" TEXT
  "email" TEXT

  Indexes {
    id [pk]
  }
}

Table "user_posix_group" {
  "user_id" TEXT [not null]
  "posix_group_name" TEXT [not null]

  Indexes {
    (user_id, posix_group_name) [pk]
  }
}

Table "experiment" {
  "experiment_id" TEXT [not null]
  "name" TEXT [not null]
  "instrument" TEXT [not null]
  "start_time" TIMESTAMPTZ [not null]
  "end_time" TIMESTAMPTZ
  "pi_id" TEXT [not null]
  "leader_account" TEXT [not null]
  "posix_group" TEXT [not null]
  "description" TEXT
  "fetched_at" TIMESTAMPTZ [not null, default: `now()`]

  Indexes {
    experiment_id [pk]
    pi_id [name: "ix_experiment_pi_id"]
  }
}

Table "experiment_analysis_queue" {
  "experiment_id" TEXT [not null]
  "queue" TEXT [not null]

  Indexes {
    (experiment_id, queue) [pk]
  }
}

Table "experiment_slack_channel" {
  "experiment_id" TEXT [not null]
  "channel" TEXT [not null]

  Indexes {
    experiment_id [pk]
  }
}

Table "questionnaire" {
  "questionnaire_id" BIGSERIAL [increment]
  "experiment_id" TEXT [not null]
  "proposal" TEXT
  "category" TEXT [not null]
  "field_id" TEXT [not null]
  "field_name" TEXT
  "field_value" TEXT
  "modified_time" TIMESTAMPTZ
  "modified_uid" TEXT
  "created_time" TIMESTAMPTZ [not null]

  Indexes {
    questionnaire_id [pk]
    experiment_id [name: "ix_questionnaire_experiment_id"]
  }
}

Table "run" {
  "id" TEXT [not null]
  "run_number" INTEGER [not null]
  "experiment_id" TEXT [not null]
  "start_time" TIMESTAMPTZ
  "end_time" TIMESTAMPTZ
  "fetched_at" TIMESTAMPTZ [not null, default: `now()`]

  Indexes {
    id [pk]
    experiment_id [name: "ix_run_experiment_id"]
  }
}

Table "logbook" {
  "id" TEXT [not null]
  "experiment_id" TEXT [not null]
  "run_id" TEXT
  "created_time" TIMESTAMPTZ [not null]
  "content" TEXT
  "content_type" elog_content_type [not null]
  "tags" BLOB
  "author" TEXT [not null]

  Indexes {
    id [pk]
    experiment_id [name: "ix_logbook_experiment_id"]
    run_id [name: "ix_logbook_run_id"]
  }
}

Table "run_detector" {
  "run_id" TEXT [not null]
  "detector_id" TEXT [not null]
  "experiment_id" TEXT [not null]
  "value" TEXT [not null]

  Indexes {
    (run_id, detector_id) [pk]
    detector_id [name: "ix_run_detector_detector_id"]
    experiment_id [name: "ix_run_detector_experiment_id"]
  }
}

Table "run_production_data" {
  "run_id" TEXT [not null]
  "experiment_id" TEXT [not null]
  "n_events" BIGINT
  "n_damaged" BIGINT
  "n_dropped" BIGINT
  "start_timestamp" TIMESTAMPTZ
  "end_timestamp" TIMESTAMPTZ
  "file_count" BIGINT
  "file_size_bytes" BIGINT

  Indexes {
    run_id [pk]
    experiment_id [name: "ix_run_production_data_experiment_id"]
  }
}

Table "workflow" {
  "id" TEXT [not null]
  "experiment_id" TEXT [not null]
  "run_id" TEXT [not null]
  "def_id" TEXT [not null]
  "user_id" TEXT [not null]
  "status" TEXT [not null]
  "submit_time" TIMESTAMPTZ [not null]
  "tool_id" BIGINT
  "log_file_path" TEXT

  Indexes {
    id [pk]
    def_id [name: "ix_workflow_def_id"]
    experiment_id [name: "ix_workflow_experiment_id"]
    run_id [name: "ix_workflow_run_id"]
    user_id [name: "ix_workflow_user_id"]
  }
}

Ref:"user"."id" < "pi"."id" [update: no action, delete: cascade]

Ref:"posix_group"."name" < "user_posix_group"."posix_group_name" [update: no action, delete: cascade]

Ref:"user"."id" < "user_posix_group"."user_id" [update: no action, delete: cascade]

Ref:"pi"."id" < "experiment"."pi_id" [update: no action, delete: no action]

Ref:"posix_group"."name" < "experiment"."posix_group" [update: no action, delete: no action]

Ref:"experiment"."experiment_id" < "experiment_analysis_queue"."experiment_id" [update: no action, delete: cascade]

Ref:"experiment"."experiment_id" < "experiment_slack_channel"."experiment_id" [update: no action, delete: cascade]

Ref:"experiment"."experiment_id" < "questionnaire"."experiment_id" [update: no action, delete: cascade]

Ref:"experiment"."experiment_id" < "run"."experiment_id" [update: no action, delete: cascade]

Ref:"experiment"."experiment_id" < "logbook"."experiment_id" [update: no action, delete: cascade]

Ref:"run"."id" < "logbook"."run_id" [update: no action, delete: set null]

Ref:"detector"."id" < "run_detector"."detector_id" [update: no action, delete: restrict]

Ref:"experiment"."experiment_id" < "run_detector"."experiment_id" [update: no action, delete: cascade]

Ref:"run"."id" < "run_detector"."run_id" [update: no action, delete: cascade]

Ref:"experiment"."experiment_id" < "run_production_data"."experiment_id" [update: no action, delete: cascade]

Ref:"run"."id" < "run_production_data"."run_id" [update: no action, delete: cascade]

Ref:"workflowdefinition"."id" < "workflow"."def_id" [update: no action, delete: restrict]

Ref:"experiment"."experiment_id" < "workflow"."experiment_id" [update: no action, delete: cascade]

Ref:"run"."id" < "workflow"."run_id" [update: no action, delete: restrict]

Ref:"user"."id" < "workflow"."user_id" [update: no action, delete: restrict]
